### ISSUE TITLE
Can I create h3 inside form?

### ISSUE THREAD

**Issue by gsiradze** [guillotinaweb/ngx-schema-form#157]
I'm using that [getting started code](https://github.com/makinacorpus/angular2-schema-form#getting-started)

```
  mySchema = {
    "properties": {
      "title": {
        "label": "Title",
        "type": "string",
        "description": "Title"
      },
      "email": {
        "type": "string",
        "description": "email",
        "format": "email"
      },
      "password": {
        "type": "string",
        "description": "Password"
      },
    },
    "required": ["email","password","rememberMe"]
  };
  myModel = {email:" john.doe@example.com", password: 'ss'};

  <sf-form [schema]="mySchema" [model]="myModel"></sf-form>
```

and I want to generate `h3` inside form. Can't I do something like that?

    "title": {
        "label": "Title",
        "type": "h3",
        "description": "Title"
      }

**Comment by ebrehault** [comment]
I guess this h3 is supposed to prefix a sub-part of your form, so that's pretty much what a fieldset legend would do.
I would recommend to stick with the fieldset / legend regular markup (semantically better, and you can style the legend so it looks like a h3), but if you prefer h3, you can derivate and customize the fieldset widget.

**Comment by Giola94** [comment]
Actually I want to generate h3, div etc outside of form. Can't I do that?

**Comment by ebrehault** [comment]
oh outside yes sure, in your calling component template:
```
<h3>My form</h3>
<sf-form [schema]="schema"></sf-form>
```
