### ISSUE TITLE
have example for "Validation handled by z-schema "?

### ISSUE THREAD

**Issue by JianhuisHuang** [guillotinaweb/ngx-schema-form#282]
have example for "Validation handled by z-schema "? @guillotinaweb thanks.

**Comment by daniele-pecora** [comment]
Feel free to [fork this at Stackblitz](https://stackblitz.com/edit/ngx-schema-form-customs)

**Comment by JianhuisHuang** [comment]
@daniele-pecora  thanks.I will try, if have any question I will @ you

**Comment by JianhuisHuang** [comment]
Hi @daniele-pecora , that is no style for input when have error or require.  need to import any style files? Or must to write it myself by hand those error? like this png
![image](https://user-images.githubusercontent.com/46215903/57567702-e6fa3700-740f-11e9-883f-67cb7e79634c.png)

**Comment by daniele-pecora** [comment]
Hi @JianhuisHuang,
since it is a custom ui widget you would handle the styles for the states `valid` and `invalid` by yourself.

Hint: 
The `input` field gets some classes set by the angular control `ng-dirty` and `ng-invalid`.

<img width="1045" alt="validity-states" src="https://user-images.githubusercontent.com/2026072/57570645-99c49800-7404-11e9-98e0-b956231ef6be.png">

**Comment by JianhuisHuang** [comment]
thanks @daniele-pecora  it's works on custom widget but not work on default widget. And can you show me example for [Advanced validation](https://github.com/guillotinaweb/ngx-schema-form#advanced-validation) with default widget ?

**Comment by daniele-pecora** [comment]
The [demo project at stackblitz.com](https://stackblitz.com/edit/ngx-schema-form-customs) now contains an example on [how to do advanced validation](https://stackblitz.com/edit/ngx-schema-form-customs?file=src%2Fapp%2Fmyform%2Fschema-form-validators.ts).  

To make the message shown up with the built-in validation you must use an error-code that the schema validator does support.   
Since the schema validator may be overridden it depends on the schema validator you are using.
Per default the schema validator [Z-Schema](https://github.com/zaggino/z-schema/) is used and    
the supported [error codes are here](https://github.com/zaggino/z-schema/blob/master/src/Errors.js).

So your error object that would be returned by the validation function should look llike:

```
const a = (the_field_value, theFieldProperty, theFormPropertyGroup) => {
  if (!valid) {
    const error = {
      code: 'INVALID_FORMAT', // this should be one of supported error codes
      path: `#/my-property`,
      message: 'My custom validation error message',
      params: [the_field_value]
    }
    return error
  }
}
```

**Comment by JianhuisHuang** [comment]
Hi @daniele-pecora  this demo works for me but must write widget myself, like this png 
![image](https://user-images.githubusercontent.com/46215903/57742755-fff73680-76f4-11e9-86d4-353accabcb73.png)
And it's possible support to change default error message? example change message "xxxx" for the error code OBJECT_MISSING_REQUIRED_PROPERTY. Like this png 
![image](https://user-images.githubusercontent.com/46215903/57742954-ab07f000-76f5-11e9-817a-2835eb619023.png)

**Comment by daniele-pecora** [comment]
It may be possible depending on which schema validator you do use.

In case of Z-Schema you may find your answer at [their github repo](https://github.com/zaggino/z-schema/blob/master/README.md).

In a similar case I had to provide an enhanced `SchemaValidatorFactory` to being able to change the behaviour of the json schema validator.

```
{provide: SchemaValidatorFactory, useClass: MyEnhancedZSchemaValidatorFactory},

```
