### ISSUE TITLE
no return field if value is empty

### ISSUE THREAD

**Issue by 13776668267** [guillotinaweb/ngx-schema-form#292]

**Comment by daniele-pecora** [comment]
I think this issue should be deleted as there are not enough information provided.
@ebrehault

**Comment by ebrehault** [comment]
absolutely

**Comment by AviFix** [comment]
For example, let say I have a form with 2 fields name and age.
clicking on the save button triggers a custom action that gets a "property" object.
property.value contains the form data.

The problem is if I edit the form and leave the input empty, I expect to get an empty value, instead, the empty property doesn't exist in the property.value
