### ISSUE TITLE
Large number input fields behaving oddly

### ISSUE THREAD

**Issue by ymeunierIGT** [guillotinaweb/ngx-schema-form#471]
I noticed a problem with users entering a large value into our custom number input widget. Once you entered more than 16 digits the widget starts to display odd values, until it resets itself to a blank input. This can also be reproduced using the demo page available on the main page, and enter in more than 16 digits into the zip input field.

In general this isn't really a problem for us, we tweaked our custom widget to limit to 16 digits as this is more than we currently need in all our use cases, but is this expected behavior?

**Comment by ebrehault** [comment]
I assume it is because JavaScript cannot handle integers larger than 2^53.

I think you might be using an integer value for a wrong reason.
Typically, a ZIP code is *not* really an integer. Semantically, it is more a string value made of numbers.

So maybe you could use a string value with a pattern checking it contains only numbers.
